version: 2
updates:
  - package-ecosystem: gomod
    directory: /rest
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /server
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /examples/rest
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily